/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, ng-bootstrap Accordion collapsed, at
* https://www.jitblox.com/project/gMu8rK1Q8K/ng-bootstrap-accordion-collapsed
*/

import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { NgbAccordionModule } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  imports: [NgbAccordionModule, CommonModule]
})
export class AppComponent {
  public isCollapsed: boolean = false;

  constructor() {}
}
